FORMAT: A1
HOST: https://api.diplserver.zbytocnosti.dev/api

# API na rozpoznávanie ľudských tvár

Technická dokumentácia opisuje jednotlivé metódy systému. Každá metóda je zaradená do skupín a má vlastný endpoint (URL)

## Autentifikácia
 - API používa basic token autorizáciu
 - Token vyprší každý 12 hodín
 - Token MUSÍ byť poskytované v HTTP hlavičke `Authorization`
 - Token MUSÍ byť poskytnuté všetky požiadavky, ktoré vyžadujú autentifikáciu

### Príklad hlavičky
```
Authorization: Base aGVubzpoZW5vMDA3
```

Pri prihlásenie reťazec je kombinácia používateľského mena a hesla s jedným dvojbodkou: `username:password`.
Reťazec je zakódovaný pomocou Base64. 

Po prihlásený na vystúp dostaneme token. Požiadavky ktoré vyžadujú autentifikáciu potrebujú zakódovať token: `token:`

## Typ médii
API používa JSON formát na požiadavky a na odpovede.

## Formát dátumu a času
Všetky výmeny údajov a údajov týkajúcich sa času MUSÍ byť vykonaná podľa normy ISO 8601 a uložená v UTC. 

Pri návrate údajov a údajov týkajúcich sa času MUSÍ byť použité formát YYYY-MM-DDThh: mm: ssZ"

## Stavové kódy a chyby

API používa na komunikáciu s používateľom HTTP stavové kódy.

+ `200 OK` - Odpoveď na úspešné požiadavky
+ `201 Created` - Odpoveď na POST, ktorá vedie k vytvoreniu.
+ `204 No Content` - Ak v odpovedi nie je obsah. Väčšinou sa používa ako odpoveď na úspešnú požiadavku DELETE.
+ `400 Bad Request` - Požiadavku server nemohol pochopiť v dôsledku nesprávnej syntaxe. Klient by namalo opakovať žiadosť bez úprav.
+ `401 Unauthorized` - Ak nie sú poskytnuté žiadne alebo neplatné podrobnosti o autentifikácii.
+ `403 Forbidden` - Žiadosť bola platná, ale server odmieta konať. Používateľ nemusí mať potrebné povolenie pre zdroj.
+ `404 Not Found` - Ak sa požaduje neexistujúci zdroj.
+ `405 Method Not Allowed` - Neplatná HTTP metóda použitá v žiadosti.
+ `422 Unprocessable Entity` - Ak overenia vstupov je neplatná.
+ `500 Internal Server Error` - Keď API nemôže spracovať požiadavky alebo existuje iný problém v systéme.

### Príklad na štandardnú chybovú hlásku

```json
{
	"code": 500,
	"message": "Unable to find file in your request!"
}
```

### Príklad na validačnú chybu

```json
{
	"message": "Validation error",
	"code": 422,
	"errors": {
		"password": "This value should not be blank."
	}
}
```

# Group Token

## Tokens [/tokens]



### Získaj token [GET]

Funkcia slúží na vytvorenie autentifikačného tokenu ktoré potrebujeme pri dalšom volaný. Autentifikačný token je potrebné pre endpointy ktoré sú chránené s autentifikáciou.

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 200 (application/json)
	+ Attributes
		+ token: `eyJhbGciOiJIUzI1NiIsImlhdCI6MTQ5NDI1OTIyOCwiZXhwIjoxNDk0MzE5MjI4fQ.eyJpZCI6MTB9.VIxysMbqqO8qgiRL27WDNEEUf96G-0qzWcRmLVNHL7w` (string) - Autorizačný token


# Group Používatelia

## Používatelia [/users/]

### Zoznam používateľov [GET]

Zoznam všetkých používateľov. Funkcia je dostupné len pre administrátora

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 200 (application/json)
    + Attributes (array[User], required)

### Registrácia používateľa [POST]

Registrácia nového používateľa. Používateľské údaje sa uložia do databázy. Po úspešnom registrácii používateľ môže sa prihlasovať

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Nie |

+ Request (application/json)
    + Attributes
        + username: `benkohenrich@gmail.com` (string, required) - Používateľské meno formou e-mail
        + password: `MagicPassword` (string, required) - Heslo
        + name: `Henrich Benkő` (string, optional) - Meno používateľa
        + avatar: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, optional) - Hlavná fotografia používateľa v base64

+ Response 200 (application/json)
    + Attributes (array[User], required)

## Detail používateľa [/users/{user_id}/]

+ Parameters
	+ user_id: `1` (number, required) - Identifikátor používateľa

### Detail používateľa [GET]

Získavanie údajov o používateľa pomocou identifikátora. Administrátor má právo získať údaje pre každý používateľ. 

Bežný používateľ môže vytiahnuť vlastné údaje len pomocou vlastného identifikátora.
  
| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 200 (application/json)
    + Attributes (User, required)
        + images (array[Image], optional)

### Zmena údajov používateľa [PUT]

Každý používateľ pomocou vlastného identifikátora má prvo zmeniť vlastné údaje.

Administrátor má možnosť zmeniť údaje každému používateľovi v systéme.

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes
        + name: `Henrich Benkő` (string, required) - Meno používatela
        + password: `MagicPassword` (string, required) - Heslo
        + avatar: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, optional) - Hlavná fotografia používateľa v base64

+ Response 200 (application/json)
    + Attributes (User, required)

## Vlastný profil [/users/me/]

### Vlastný profil [GET]

Endpioint slúži na získanie vlastných používateľských údajov. Táto metóda nepotrebuje identifikátor používateľa. Pomocou hlavičky autorizácie vytiahne údaje. 

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 201 (application/json)
    + Attributes (User, required)
        + images (array[Image], optional)
        
## Používateľské obrázky [/users/face/]

### Uložiť obrazok pre používateľa [POST]

Používateľ po registrácii musí poslať minimálne 10 fotiek aby bol rozpoznávací systém úspešný. Endpoint slúží na lozenie obrázka do databázy.

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes (FaceTypes, required)
        + face: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, required) - Obrázok v base64

+ Response 201 (application/json)
    + Attributes
        + face_image: `http://diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútna URL-ka ku obrázku


## Používateľské procesy [/users/logs/]

### Zoznam vlastných procesov [GET]

Každý používateľ ktorý používa systém rozpoznania má uloženú každú požiadavku v databáze. Tieto známi obsahujú vstupné a výstupné dáta. 

Pomocou týchto údajov má možnosť prezerať nastavenia a výsledky rozpoznania.

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 200 (application/json)
    + Attributes (array[Process], optional)

## Používateľský process [/users/logs/{log_id}]

+ Parameters
	+ log_id: `b429b294-ac24-423f-bb5a-a90998dd7612` (string, required) - Identifikátor procesu UUID4

### Detail processu [GET]

Detailné údaje jednotlivých procesov

**Endpoint informácia**

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 200 (application/json)
    + Attributes (array[ProcessDetail], optional)

# Group Obrázky

## Obrázky [/images/{image_id}]

Zobraziť obrázok pomocou URL. 

+ Parameters
    + image_id: 1 (number, required) - Identifikátor obrázku

### Zobraziť obrázok [GET]

Endpoint na zobrazenie obrázkov. Táto metóda nepotrebuje autorizáciu aby mali všetky používatelia dostupné obrázky

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Nie |

+ Response 200 (image/jpeg)

### Vymazať obrázok [DELETE]

Každý používateľ má právo vymazať vlastné obrázky. 

Administrátor má pravo vymazať obrázky iných používateľov

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Response 204 

# Group Extrakcia príznakov

## LBP [/api/lbp/face/]

### Vytvorenie histogramu pomocou LBP [POST]

Metoda vygeneruje z poslaného obrázka histogram pomocou LBP.

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes (FaceTypes, required)
        + face: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, required) - Obrázok v base64
        + recognition_settings: (LbpRecognitionSettings, required)

+ Response (application/json)
    + Attributes
        + metadata:
            + estimated_time: 0 (number, optional) - Čas behu požiadavky
        + process:
            + extraction: (LbpExtraction, optional)
            + uuid: `d184dc16-7ccc-4bde-9dbc-7cec8ac0b204` (string, required) - UUID procesu
            
# Group Rozpoznávanie

## LBP histogram [/api/lbp/]

### LBP histogram [POST]

Metoda na rozpoznávanie. Pomocou LBP vy-extrahujeme dáta (histogramy) z obrázka podla nastavenia. Klasifikačný algoritmus porovná s ostatnými obrázkami v databáze. 
Na výsledok dostaneme rozpoznaný obrázok a pravdepodobnosť totožnosti.

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes (FaceTypes, required)
        + face: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, optional) - Obrázok v base64
        + histogram: `[ 0.5 0.5 0.8 0.9]` (string, optional) - Histogram vygenerované na klientskej časti.
        + extraction_settings: (LbpExtractionSettings, required)
        + recognition_settings: (LbpRecognitionSettings, required)

+ Response (application/json)
    + Attributes
        + metadata:
            + estimated_time: 0 (number, optional) - Čas behu požiadavky
        + process:
            + extraction: (LbpExtraction, optional)
            + recognition: (LbpRecognition, optional)
            + uuid: `d184dc16-7ccc-4bde-9dbc-7cec8ac0b204` (string, required) - UUID procesu
        

## PCA eigenfaces [/api/eigen/]

### PCA eigenfaces [POST]

Metoda na rozpoznávanie. Pomocou PCA vy-extrahujeme dáta (eigenvektory) z obrázka podla nastavenia. Klasifikačný algoritmus porovná s ostatnými obrázkami v databáze. 
Na výsledok dostaneme rozpoznaný obrázok a pravdepodobnosť totožnosti.

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes (FaceTypes, required)
        + face: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, required) - Obrazok v base64
        + extraction_settings: (PcaExtractionSettings, required)
        + recognition_settings: (PcaRecognitionSettings, required)

+ Response (application/json)
    + Attributes
        + metadata:
            + estimated_time: 0 (number, optional) - Čas behu požiadavky
        + process:
            + recognition: (PcaRecognition, optional)
            + uuid: `d184dc16-7ccc-4bde-9dbc-7cec8ac0b204` (string, required) - UUID procesu

## LDA fisherfaces [/api/fisher/]

Metoda na rozpoznávanie. Pomocou LDA vy-extrahujeme dáta (fishervektory) z obrázka podla nastavenia. Klasifikačný algoritmus porovná s ostatnými obrázkami v databáze. 
Na výsledok dostaneme rozpoznaný obrázok a pravdepodobnosť totožnosti.

### LDA fisherfaces [POST]

| Vlastnosť               |     |
|-------------------------|-----|
| Vyžaduje autentifikáciu | Áno |

+ Request (application/json)
    + Attributes (FaceTypes, required)
        + face: `data:image/jpeg;base64,/9j/4AAQSkZJRgAB...` (string, required) - Obrazok v base64
        + extraction_settings: (LdaExtractionSettings, required)
        + recognition_settings: (LdaRecognitionSettings, required)

+ Response (application/json)
    + Attributes
        + metadata:
            + estimated_time: 0 (number, optional) - Čas behu požiadavky
        + process:
            + recognition: (LdaRecognition, optional)
            + uuid: `d184dc16-7ccc-4bde-9dbc-7cec8ac0b204` (string, required) UUID procesu
            
# Data Structures

## User (object)
+ id: `1` (number, required) - Identifikátor používateľa
+ name: `Henrich Benko`, (string, required) - Meno používateľa
+ username: `benkohenrich@gmail.com` (string, required) - Používateľské meno
+ main_photo: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, optional) - Hlavná fotka používateľa

## Image (object)
+ id: `1` (number, required) - Identifikátor obrázka
+ url: `http://diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútná cesta ku obrázku

## Process (object)
+ uuid: `a1c2e6b9-d904-4a6a-8d82-a44c44f24da4` (string, required) - UUID procesu
+ user_id: 1 (number, required) - Identifikátor používateľa
+ algorithm_type: `Eigenfaces PCA` (string, required) - Meno používaného algoritmu
+ algorithm_type_code: `eigenfaces` (string, required) - Kód používaného algoritmu
+ created_at: `2016-08-01 12:00` (string, required) - Dátum vytvorenia

## ProcessDetail (object)
+ algorithm_type_code: `eigenfaces` (string, required) - Kód algoritmu. Systém automatický nastaví podla endpointu.
+ code: `recognition` (enum[string], required) - Typ procesu ktorý systém vykonal
    + Default: `extraction`
    + Members
        + `recognition`
        + `extraction`
+ errors: (array, optional) - Pole obsahuje chyby počas požiadavky
+ inputs: (array, optional) - Pole obsahuje všetky poslané vstupy
+ responses: (array, optional) - pole obsahuje odpoveď na požiadavku

## LbpExtraction
+ images: (ExtractionImage, optional)
+ metadata
    + process_time: 0 (number, optional) - Čas behu procesu
+ parameters: (LbpExtractionSettings, required)
    + histogram: `[0.0449, 0.0332, 0.0233, 0.018, 0.0174, 0.0184, 0.0186, 0.018, 0.0216, 0.0209, 0.0298, 0.0417, 0.0309, 0.025, 0.0179, 0.0148, 0.0054, 0.0061, 0.0029, 0.0027, 0.004, 0.0068, 0.0154, 0.0287, 0.0196, 0.514]` (string, required) - Vygenerovaný histogram 
 
## LbpRecognition
+ images: (RecognitionImage, optional)
+ metadata
    + process_time: 0 (number, optional) - Čas behu procesu
+ parameters: 
    + (LbpExtractionSettings, required)
    + (LbpRecognitionSettings, required)
	+ predict_user: (PredictUser, required)
    + recognize_histogram: `[0.0449, 0.0332, 0.0233, 0.018, 0.0174, 0.0184, 0.0186, 0.018, 0.0216, 0.0209, 0.0298, 0.0417, 0.0309, 0.025, 0.0179, 0.0148, 0.0054, 0.0061, 0.0029, 0.0027, 0.004, 0.0068, 0.0154, 0.0287, 0.0196, 0.514]` (string, required) - Vygenerovaný histogram
    + similarity_percentage: 99.99 (number, required) - Vypočítaný pravdepodobnosť totožnosti
    + total_compared_histograms: 254 (number, required) - Počet porovnaných histogramov 

## LbpExtractionSettings
+ radius: 8 (number, required) - Atribút rádius na nastavenie LBP modelu
+ points: 24 (number, requeired) - Atribút počet bodov v okruhu na nastavenie LBP modelu
+ method: `uniform` (enum[string], required) - Atribút metód na nastavenie LBP modelu
    + Default: `default`
    + Members
        + `default`
        + `ror`
        + `uniform`
        + `nri_uniform`
        
## LbpRecognitionSettings
+ algorithm:`correlation` (enum[string], required) - Klasifikačný algoritmus
    + Default: `svm`
    + Members
        + `svm`
	    + `correlation`
	    + `chi-squared`
	    + `intersection`
	    + `bhattacharyya`
	    + `euclidean`
	    + `manhattan`
	    + `chebysev`
	    + `cosine`
	    + `braycurtis`

## ExtractionImage
+ full: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, optional) - Absolútna cesta ku obrázku ktorý bol poslaný bez výrezu tvári.
+ face: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútna cesta ku obrázku ktorý bol poslaný s výrezom tvári alebo systém detegoval a vyrezal tvár.
+ face_grey: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútna cesta ku obrázka ktorý prevedený do grayscale.
+ face_equalized: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútna cesta ku obrázka ktorý prehodený do histogramovu ekvalizáciu.
+ histogram_graph: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, required) - Absolútna cesta ku vygenerovaný graf z histogramu
## RecognitionImage
+ compared_image:`http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, optional) - Absolútna cesta ku obrázku ktorý bol poslaný na rozpoznávanie
+ predict_image: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, optional) - Absolútna cesta ku rozpoznanú obrázku
      
## PcaRecognition
+ images: (RecognitionImage, optional)
+ metadata
    + process_time: 0 (number, optional) - Čas behu procesu
+ parameters: 
    + (PcaExtractionSettings, required)
    + (PcaRecognitionSettings, required)
	+ predict_user: (PredictUser, required)
    + recognize_eigenfaces: `[0.0449, 0.0332, 0.0233, 0.018, 0.0174, 0.0184, 0.0186, 0.018, 0.0216, 0.0209, 0.0298, 0.0417, 0.0309, 0.025, 0.0179, 0.0148, 0.0054, 0.0061, 0.0029, 0.0027, 0.004, 0.0068, 0.0154, 0.0287, 0.0196, 0.514]` (string, required) - Vygenerovaný histogram
    + similarity_percentage: 99.99 (number, required) - Vypočítaný pravdepodobnost totožnosti
    + total_compared_eigenfaces: 254 (number, required) - Počet porovnaných eigenvektorov
    + distance `0.6242404956290856` (string, optional) - Vypočítaný vzdialenosť (minimálny).

## PcaExtractionSettings
+ number_components: 200 (number, required) - Počet komponentov, atribút pre PCA model
+ whiten: true (boolean, required) - Atributa pre PCA model.
+ method: `randomized` (enum[string], required) - Metoda SVC pre trénovanie PCA modelu. 
    + Default: `randomized
    + Members
        + `randomized`
        + `auto`
        + `full`
        
## PcaRecognitionSettings
+ algorithm:`euclidean` (enum[string], required) - Klasifikačný algoritmus
    + Default: `svm`
    + Members
        + `svm`
	    + `euclidean`
	    + `manhattan`
	    + `chebysev`
	    + `cosine`
	    + `braycurtis`

## LdaRecognition
+ images: (RecognitionImage, optional)
+ metadata
    + process_time: 0 (number, optional) - Čas behu procesu
+ parameters: 
    + (PcaExtractionSettings, required)
    + (PcaRecognitionSettings, required)
	+ predict_user: (PredictUser, required)
    + recognize_eigenfaces: `[0.0449, 0.0332, 0.0233, 0.018, 0.0174, 0.0184, 0.0186, 0.018, 0.0216, 0.0209, 0.0298, 0.0417, 0.0309, 0.025, 0.0179, 0.0148, 0.0054, 0.0061, 0.0029, 0.0027, 0.004, 0.0068, 0.0154, 0.0287, 0.0196, 0.514]` (string, required) - Vygenerovaný histogram
    + similarity_percentage: 99.99 (number, required) - Vypočítaný pravdepodobnosť totožnosti.
    + total_compared_fisherfaces: 254 (number, required) - Počet porovnaných fishervektorov.
    + distance `0.6242404956290856` (string, optional) - Vypočítaný vzdialenosť (minimalný).

## LdaExtractionSettings
+ number_components: 200 (number, required) - Počet komponentov, atribút pre LDA model
+ tolerance: 0.01 (number, required) - Tolerancia chybovosti.
  
## LdaRecognitionSettings
+ algorithm:`euclidean` (enum[string], required) - Klasifikačný algoritmus
    + Default: `svm`
    + Members
        + `svm`
	    + `euclidean`
	    + `manhattan`
	    + `chebysev`
	    + `cosine`
	    + `braycurtis`



## PredictUser
+ id: 4 (number, required) - Identifikátor rozpoznaného používateľa
+ email: `terminator` (string, required) - Email rozpoznaného používateľa
+ name: `Arnold Schwarzenegger` (string, optional) - Meno rozpoznaného používateľa
+ main_image: `http://api.diplserver.zbytocnosti.sk/api/images/1/` (string, optional) - Hlavná fotka rozpoznaného používateľa   

## FaceTypes
+ face_type: `full` (enum[string], required) - Typ poslaného obrázku
    + Default: `full`
    + Members
        + `full`
        + `face`
        + `full_gray`
        + `face_gray`